### PR TITLE
Preparation for Neovim v0.8 Release

### PR DESCRIPTION
**Pull request by mehalter**
This is a heavy WIP just to keep on top of breaking changes on nightly as they come up. This branch should be considered unstable and in development

This has a small breaking change for people who do customization to `feline`. Instead of just a `plugins.feline` table since there are 2 `setup` calls we now have `plugins.feline.statusline` and `plugins.feline.winbar` for configuring each of the two bars.

### CODE REVIEW

**Comment by bryant-the-coder** [comment]
@mehalter ur fast af 😂

**Comment by famiu** [comment]
You can just use `vim.cmd` with a table argument instead of passing an empty opts table to `nvim_cmd` thanks to https://github.com/neovim/neovim/pull/18523

**Comment by mehalter** [comment]
Oh awesome @famiu ! Thanks for letting me know!

**Comment by mehalter** [comment]
Development moved to #715

**Pull request closed without merging**
