### PR TITLE
refactor(utils): create find_config_files function as file helper utility

### PR DESCRIPTION
**Pull request by orhun**
I needed this function in my custom configuration but it was not possible to call it. So I created a new utils module named `file` and moved it to there.

Let me know if you prefer to have it somewhere else.

Thanks!

### CODE REVIEW

**Comment by mehalter** [comment]
Thanks for the recommendation! Sadly, this function will be removed either way on April 1, 2024 (in like 4 weeks) because it is not applicable to the upcoming AstroNvim v4 release. For this reason, I wouldn't recommend upstreaming this at the moment to the utilities nor using any such utility in your user configuration. As a work around, you actually can access that function from within your user config. Here is an example `user/init.lua` file that access it:

```lua
return {
  mappings = function(maps)
    local find_config_files = maps.n["<leader>fa"][1]
    -- do whatever you need...
    
    return maps
  end
}
```

**Comment by orhun** [comment]
Ah I see! Thanks for sharing the solution. Looking forward to the v4 update - I hope the migration won't be painful!

**Comment by mehalter** [comment]
I also hope this 😅 it definitely will be a bit involved haha

**Comment by orhun** [comment]
haha let's see 😄 (💀 💀 💀 )

**Comment by mehalter** [comment]
If you are curious, check out the announcements on the official Discord server. Yesterday we finally got out the first draft of the migration guide :)

**Comment by orhun** [comment]
ok just checked and it indeed looks painful ☠️ I think I'm going to stick with v3 for a while until it breaks. My humble opinion is that it is annoying to re-setup everything while migrating to new versions. However, as a fellow open source developer I see that you're working on improvements that might need that - so I completely understand it. Just wanted to rant here a bit and say that it is just a bit annoying :D

Thanks for your work on this nice neovim config :3

**Comment by mehalter** [comment]
Yeah I really hate it 😅 This is the first really huge breaking change that requires re-setup which is unfortunate but sorta unavoidable in this situation to future proof the project and maintain stability. Our biggest thing is definitely trying to hold off as much as possible any sort of breaking changes to minimize this type of annoyance. Luckily we were able to hold off any breaking changes (v3 -> v4) for over a year at least 😅

**Pull request closed without merging**
