### PR TITLE
chore(readme): fix incorrect url in link

### PR DESCRIPTION
**Pull request by SunHuawei**

### CODE REVIEW

**Review by mehalter — CHANGES_REQUESTED** [review]
Thanks for catching this! Could you please reword your commit message to follow the Conventional Commit spec? Something like `fix(readme): fix incorrect url in link`? After that the tests will be able to pass and I can merge this. 

You can find instructions for this in our contribution guidelines: https://github.com/AstroNvim/AstroNvim/blob/main/.github/CONTRIBUTING.md

**Comment by SunHuawei** [comment]
@mehalter , thanks! Please take a look again.

**Comment by mehalter** [comment]
@SunHuawei it looks like you changed the title of the pull request, not the actual commit text. Check out the contribution guide if you have questions about rewording commits

**Comment by mehalter** [comment]
I'll go ahead and merge this and fix the commit message on `nightly`

**Pull request merged**
