### PR TITLE
Fixed Bufferline "modified_icon" highlight on inactive tabs.

### LINKED ISSUE #937: Bufferline, background behind the "modified_icon" is highlighted, when buffer is not active.
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v1.9.0-5-g09c5d47

### Neovim version (>= 0.7)

v 0.7.2

### Operating system/version

Kali Rolling 5.18.0-kali5-amd64

### Describe the bug

After modifying the buffer, and switching to another, the buffer tab changes the color, but a portion behind the "modified_icon" remains highlighted:

### Steps to Reproduce

1. Open two or more files.
2. Edit one file.
3. Switch buffer to another file.

### Expected behavior

The whole buffer tab should change the color.

### Screenshots

Снимок экрана 2022-09-02 в 13 58 26

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ScriptGenius**
Fixed #937 issue.

### CODE REVIEW

**Comment by ScriptGenius** [comment]
This commit messes up with the "red" color.

**Review by mehalter — CHANGES_REQUESTED** [review]
Thanks for the contribution! This looks great. Could you please squash the 2 commits into a single commit and then reword the commit message to follow Conventional Commit specification?

**Comment by mehalter** [comment]
Oh I forgot to mention, if you have any questions about this, there are instructions in the contribution guidelines on the repo :)

**Review by mehalter — APPROVED** [review]
LGTM

**Pull request merged**
