### PR TITLE
fix(lsp): condition to check if lsp server supports semantic tokens

### PR DESCRIPTION
**Pull request by RayJameson**
Fixes Issue #2020

Bugs Fixed:
- Wrong condition check for semantic tokens support before enabling them

### CODE REVIEW

**Review by mehalter — APPROVED** [review]
This is great! Thank you so much!

**Review by mehalter — CHANGES_REQUESTED** [review]
Could you please format the code with `stylua` so the tests pass?

**Review by mehalter — APPROVED** [review]
Looks great! Thank you so much!

**Comment by RayJameson** [comment]
You are welcome, happy to be useful to my favorite community

**Pull request merged**
