### PR TITLE
chore: fix typo in readme

### PR DESCRIPTION
**Pull request by tusharxoxoxo**
chore: fix typo in readme

### CODE REVIEW

**Review by mehalter — CHANGES_REQUESTED** [review]
Thank you for your contribution! Could you please reword your commit message to follow the c
Conventional Commit specification as described in the Contribution Guidelines? It should be something like this `chore: fix typo in readme`

If you do not know how to do this, there are instructions in the Contribution Guidelines.

**Comment by tusharxoxoxo** [comment]
like this

**Comment by mehalter** [comment]
@tusharxoxoxo No, you need to reword the commit message not the Pull Request name. Please see the Contribution Guidelines

**Comment by mehalter** [comment]
https://github.com/AstroNvim/AstroNvim/blob/main/.github/CONTRIBUTING.md#how-to-remove-squash-or-edit-commits-from-your-pr

**Review by tusharxoxoxo — COMMENTED** [review]
chore: fix typo in readme

**Review by tusharxoxoxo — COMMENTED** [review]
🚩 Grammatical Error

**Comment by tusharxoxoxo** [comment]
now??

**Review by mehalter — APPROVED** [review]
LGTM

**Comment by mehalter** [comment]
Yup thanks for the contribution!

**Pull request merged**
