### PR TITLE
Add bufferline to README

### PR DESCRIPTION
**Pull request by jayp0521**

### CODE REVIEW

**Review by mehalter — CHANGES_REQUESTED** [review]
Thank you for your contribution. Could you please reword your commit message to meet the conventional commit specification as detailed in the [Contribution Guidelines](https://github.com/AstroNvim/AstroNvim/blob/main/.github/CONTRIBUTING.md)

Once this is reworded the checks should pass and I'll be able to approve the PR.

**Comment by mehalter** [comment]
The commit message should be something long the lines of `chore: add bufferline to readme`

**Comment by jayp0521** [comment]
should be good. sorry about that

**Review by mehalter — APPROVED** [review]
LGTM

**Pull request merged**
