### PR TITLE
feat: move to mason package manager

### LINKED ISSUE #787: Migrate from nvim-lsp-installer to mason.nvim
The author of [`nvim-lsp-installer`](https://github.com/williamboman/nvim-lsp-installer) released an announcement ([see discussion thread](https://github.com/williamboman/nvim-lsp-installer/discussions/876)) about deprecating the plugin in favour of the more powerful & full-featured [`mason.nvim`](https://github.com/williamboman/mason.nvim). So, are there any plans to migrate to the latter plugin in the near future (_perhaps from AstroNvim v0.9 onwards or something_)?

P.S: It appears to me, `mason.nvim` is still in its early stages of development so it might in the best interest of everyone to wait a while before jumping ship.

### PR DESCRIPTION
**Pull request by mehalter**
This moves us to using the new Mason package manager while maintaining no breaking changes

Resolves #787

### CODE REVIEW

**Review by kabinspace — APPROVED** [review]

**Comment by mehalter** [comment]
This is going to be held off for a bit. After a lot of testing there is a significant amount of instability and bugs throughout this and it is not as stable as `nvim-lsp-installer` yet. But hopefully as development continues and more people use it, things get ironed out quickly.

**Comment by flamendless** [comment]
Why move to a new package manager though?

**Comment by mehalter** [comment]
@flamendless nvim LSP installer is deprecated and no longer receiving any updates or bug fixes to lsp

**Comment by rollingmoai** [comment]
> This is going to be held off for a bit. After a lot of testing there is a significant amount of instability and bugs throughout this and it is not as stable as `nvim-lsp-installer` yet. But hopefully as development continues and more people use it, things get ironed out quickly.

What **exactly** are the current blockers from getting this merged?

**Comment by mehalter** [comment]
@rollingmoai there is a weird error we are getting and it appears to be coming from the git-signs plugin but we don't get it without mason. So I need to find some time to investigate this and resolve it before this can be merged.

**Comment by mehalter** [comment]
Relevant announcement here: https://github.com/AstroNvim/AstroNvim/discussions/820

**Pull request merged**
